# Generated by Django 3.2.5 on 2022-03-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profil_pic',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
